/*
 Find the Difference
Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.
Example:
Input:
s = "abcd"
t = "abcde"
Output:
e
Explanation:
'e' is the letter that was added.
*/
class Solution {
    public char findTheDifference(String s, String t) {
        //Like missing number in the sum
        int sumS = 0, sumT = 0;
		char[] arrS = s.toCharArray();
		char[] arrT = t.toCharArray();
		for (int i = 0; i < arrS.length; i++) {
			sumS += arrS[i] - 'a';
			sumT += arrT[i] - 'a';
		}
		sumT += arrT[arrT.length - 1] - 'a';
		return (char) (sumT - sumS + 'a');
         /*char diff = t.charAt(t.length() - 1);
        
        for (int i = 0; i < s.length(); i ++) {
            diff ^= s.charAt(i);
            diff ^= t.charAt(i);
        }

        return diff;
        */
        /*
        HashMap <Character,Integer> map = new HashMap<>();
        for(char ch:s.toCharArray())
            map.put(ch,map.getOrDefault(ch,0) + 1);
        char c = 'a';
        for(char ch: t.toCharArray()){
            if(!map.containsKey(ch) || map.get(ch) == 0){
                c = ch;
                break;
            }
            else
                map.put(ch,map.get(ch) - 1);
        }
        return c;
        */        
    }
}